### ISSUE TITLE
Keep Getting PushyRegistrationException on Ipad IOS 17.4.1

### ISSUE THREAD

**Issue by happyshittake** [pushy/pushy-react-native#90]
We are keep getting

```
Registration failed: PushyRN.PushyRegistrationException.Error("Please enable push notifications for this app in the iOS settings.", "PUSH_PERMISSION_DENIED")
```

even though we have enabled the permission on the settings page, this happened recently, before we don't have any problem

**Comment by pushy** [comment]
Hi @happyshittake,
Thanks for reaching out. We'd be glad to assist.

We've just released version `1.0.38` of the SDK to assist with fixing this issue. Please update to the latest version of the Pushy React Native SDK by running the following command in the root directory of your project:

```
npm install pushy-react-native@latest --save
```

Then, add the following line of code **before** `Pushy.register()`:

```
Pushy.toggleIgnorePushPermissionDenial(true);
```

Please give it a try and let us know if the issue is resolved.
